### ISSUE TITLE
Disabling the internal bridge causes a seg fault and die

### ISSUE THREAD

**Issue by bevand10** [SuperFlyTV/SuperConductor#105]
**Describe the bug**
Disabling the default internal bridge causes a segmentation fault and the app to die

**To Reproduce**
1. Go to Bridges
2. Click on the Internal Bridge on/off toggle
3. App dies with this in the console:
```
$ ./SuperConductor-0.9.4-Linux-Executable.AppImage 

(superconductor:1043374): Gtk-WARNING **: 09:41:28.104: Unknown key ;gtk-application-perfer-dark-theme in /home/bevand10/.config/gtk-3.0/settings.ini
2022-10-25T08:41:28.450Z [electron] info: Starting up...
[1043433:1025/094128.682050:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Checking for update
Update for version 0.9.4 is not available (latest version: 0.9.4, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
ThreadedClass (7415) Skipping exit handler registration as no exit handler is registered
2022-10-25T08:41:30.788Z [electron] warn: Warning: TSR TSR is not initialized yet
2022-10-25T08:41:30.796Z [electron] info: TSR statReport {"reason":"timeline received","timelineStartResolve":250,"timelineResolved":252,"stateHandled":252,"done":253,"timelineSize":0,"timelineSizeOld":0,"estimatedResolveTime":20}
2022-10-25T08:41:30.796Z [electron] info: TSR Initializing device casparcg0 (5854) of type CASPARCG...
Segmentation fault (core dumped)
```

**Expected behavior**
App probably shouldn't die.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - Version 0.9.4 (see above)

**Comment by nytamin** [comment]
Thanks for reporting this!

Could you see if changing any settings for the bridge changes the behavior when you disable/enable the internal bridge? 
Try adding or removing playout devices to see if it's one specific device that cases the seg-fault?

Or try unplugging any connected streamdecks/xkeys?

**Comment by bevand10** [comment]
Hi,
It was default out-of-the box behaviour - literally download, set execute bits via `chmod a+x ./S<tab>`, exec via `./S<tab>`, toogle the IB and pop.
No other apps related to SC are installed - no Caspar etc.

**Comment by nytamin** [comment]
Thanks! The seg-fault might be tricky to troubleshoot but I'll see what I can do!

**Comment by nytamin** [comment]
Hey @bevand10 could you try the latest version, [0.9.6 ](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.9.6)and see if that helps?
It contains a few fixes that are related to USB-devices in general, it _might_ fix your issue as well.

**Comment by bevand10** [comment]
App no longer crashes when disabling the internal bridge.

![Screenshot from 2022-10-26 15-41-13](https://user-images.githubusercontent.com/5892030/198056928-2cb1f469-a8ff-4619-aa74-5249c3df8086.png)
