### ISSUE TITLE
Unable to use multiple layers/parts concurrently

### ISSUE THREAD

**Issue by Julusian** [SuperFlyTV/SuperConductor#112]
**Describe the bug**
I have two parts playing on loop, with clips on different layers. Every time one of them loops, the other one gets cleared.

It feels like only the part with the most recent 'change' is being put on the timeline

**To Reproduce**
1. Create a new rundown
2. Duplicate the default part
3. Change the layer of the clip in the duplicate part
4. Toggle the parts play as playlist/independently setting for the group
5. Start the first part playing
6. Wait a couple of seconds, and start the second part playing
7. Watch the output, and observe that only one of the clips is visible at any time

**Expected behavior**
The two parts should play concurrently without interfering with each other.

**Screenshots**
![image](https://user-images.githubusercontent.com/1327476/201766651-b4e94624-cdee-4e90-b3b6-f0ae11780713.png)

![image](https://user-images.githubusercontent.com/1327476/201766885-2ca9444d-fe5e-4868-a5ad-37a0d1239c68.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.9.6

**Additional context**

**Comment by nytamin** [comment]
I believe this have been solved in [#dbe2ea1](https://github.com/SuperFlyTV/SuperConductor/commit/dbe2ea157d4f85c590c593e42d040437a2b995d4), so should be OK in next release
