### ISSUE TITLE
Unable to add CasparCG Template

### ISSUE THREAD

**Issue by DaanPeters** [SuperFlyTV/SuperConductor#119]
Selecting the template type for the timeline object returns the following errormessage:

![image](https://user-images.githubusercontent.com/11334573/205856756-b24831b2-4680-44e7-be36-87b2a6f9a9ad.png)

**Comment by nytamin** [comment]
This should now be fixed in version `0.10.1` (the app will automatically update on next restart).
If the issue persists, please reopen this issue.
