### ISSUE TITLE
SuperConductor-0.10.1-Windows-Installer - ATEM connection broken?

### ISSUE THREAD

**Issue by lpdswe** [SuperFlyTV/SuperConductor#124]
**Describe the bug**
Latest prebuilt binaries for Windows won´t connect to ATEM switchers

**To Reproduce**
1. Download installer: "SuperConductor-0.10.1-Windows-Installer.exe"
2. Install as normal
3. Set up internal bridge to connect to a ATEM switcher
4. Connection will not get pass "Initializing" 

**Expected behavior**
Should connect as excpected

**Screenshots**
![image](https://user-images.githubusercontent.com/22725626/218476038-4c9688ca-6ada-4f2b-b065-ec0108079770.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - CPU: AMD Ryzen Threadripper PRO 5955WX
 - RAM: 128GB
 - GPU: Nvidia RTX4090

**Additional context**
Works great if building manually from master-branch and installing. Simple issue with dist-build or some dependency?

**Comment by alvancamp** [comment]
Interesting, is there anything relevant in the logs? (Located at `C:\Users\<YOUR USERNAME>\Documents\SuperConductor\Logs` on Windows).

**Comment by nytamin** [comment]
This is a strange one..

Now after spending some time to figure this out, I believe that [this new version (0.10.2-alpha.0)](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.10.2-alpha.0) might fix the issue. (It updates the threadedclass dependency which has a fix for electron.)

@lpdswe could you give it a spin on your end as well?

**Comment by nytamin** [comment]
Good to hear! I've published the fix in version 0.10.2.
