### ISSUE TITLE
Default keyboard shortcuts for next and previous incorrect

### ISSUE THREAD

**Issue by rjames1295** [SuperFlyTV/SuperConductor#126]
**Describe the bug**
The default actions of `F5` or `F6` pauses the timeline instead of previous/next.

https://github.com/SuperFlyTV/SuperConductor/blob/master/apps/app/src/lib/defaults.ts#L69

https://github.com/SuperFlyTV/SuperConductor/blob/master/apps/app/src/lib/defaults.ts#L76

**Comment by nytamin** [comment]
Thanks for reporting this!

@rjames1295 could you have a look at [this fix](https://github.com/SuperFlyTV/SuperConductor/commit/624adf8dbe83e9b8a18f218be878d9b9813d3b77), does it look correct to yuo?

**Comment by rjames1295** [comment]
@nytamin Actually, the next key should probably trigger the next action 😄 

```
...
			next: [
				{
					label: 'F5',
					fullIdentifiers: ['keyboard-F5'],
					action: 'next',
				},
			],
			previous: [
				{
					label: 'F6',
					fullIdentifiers: ['keyboard-F6'],
					action: 'previous',
				},
			],
...
```
