### ISSUE TITLE
MacOS: "A JavaScript error occurred in the main process" on startup

### ISSUE THREAD

**Issue by Saftret** [SuperFlyTV/SuperConductor#14]
**Description**
Not able to start the application on MacOS.

**To Reproduce**
1. Open app

**Error message**
> Uncaught Exception:
> Error: dlopen(/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.ZoDdHy, 0x0001): tried: '/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.ZoDdHy' (code signature in <B318D3CC-46D0-30A7-8906-77C01090490E> '/private/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.ZoDdHy' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/private/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.ZoDdHy' (code signature in <B318D3CC-46D0-30A7-8906-77C01090490E> '/private/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.ZoDdHy' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
> at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
> at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
> at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
> at Module.load (node:internal/modules/cjs/loader:982:32)
> at Module._load (node:internal/modules/cjs/loader:823:12)
> at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
> at Module.require (node:internal/modules/cjs/loader:1006:19)
> at require (node:internal/modules/cjs/helpers:93:18)
> at bindings (/Applications/SuperConductor.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
> at loadBinding (/Applications/SuperConductor.app/Contents/Resources/app.asar/node_modules/node-hid/nodehid.js:25:42)

**Screenshots**
<img width="372" alt="superc" src="https://user-images.githubusercontent.com/346144/159265499-1d585921-5a99-4ddf-b288-d8d390bd4ced.png">

**Desktop:**
 - OS: MacOS
 - Version 12.3 - Apple Silicon

**Comment by Saftret** [comment]
Sadly still not working in v0.6:
```
Uncaught Exception:
Error: dlopen(/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.5z9HiT, 0x0001): tried: '/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.5z9HiT' (code signature in <AB90D580-44E6-3C7B-9FEB-810B43A5F7DD> '/private/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.5z9HiT' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/private/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.5z9HiT' (code signature in <AB90D580-44E6-3C7B-9FEB-810B43A5F7DD> '/private/var/folders/vb/dnpj7gf12mg2dbv8vfxr83dc0000gn/T/.tv.superfly.superconductor.5z9HiT' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at bindings (/Applications/SuperConductor.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
at loadBinding (/Applications/SuperConductor.app/Contents/Resources/app.asar/node_modules/node-hid/nodehid.js:25:42)
```

Maybe these can be helpful: [https://github.com/electron-userland/electron-builder/issues/3940](https://github.com/electron-userland/electron-builder/issues/3940)
[https://github.com/pyinstaller/pyinstaller/issues/4333](https://github.com/pyinstaller/pyinstaller/issues/4333)

So possibly adding `com.apple.security.cs.disable-library-validation` to .plist file might help?

**Comment by alvancamp** [comment]
@Saftret can you try this build? I added the `disable-library-validation` entitlement to it: https://www.dropbox.com/s/tji8jxc4zk8ag7l/SuperConductor-0.6.1-macOS-Installer.dmg?dl=1

**Comment by Saftret** [comment]
@alvancamp Yes, that is working! Thanks!

**Comment by hummelstrand** [comment]
Can we consider this fixed and close the issue?
