### ISSUE TITLE
HTTP Send Problems

### ISSUE THREAD

**Issue by amwtech** [SuperFlyTV/SuperConductor#141]
I have encountered two issues with the http send device:
1) Unable to delete a parameter, the delete bin for the parameter number only deletes the key value, not the Parameter
2) The only key name that works for data entry is of the form **param0** meaning the tool can not send to most restful APIs

**To Reproduce Parameter Delete issue**
1) Add an HTTP Send device to the local bridge. The name field does not matter
2) Add an HTTP Request to a part.
3) Click the ADD PARAMETER button.
4) Click on the red bin item at the right of the Param # line. The value field clears.

**Expected behavior**
To be able to remove the parameter complete with its key and value settings.

**To Reproduce Parameter Name issue**
1) Add an HTTP Send device to the local bridge if there is not one already present.
2) Add an HTTP Request to a part.
3) Click the ADD PARAMETER button. The blank entry form for the parameter is shown as below.

<img width="292" alt="HTTP Send Blank Parameter" src="https://user-images.githubusercontent.com/86308191/235373517-45d36d57-a7ea-439c-a903-7f8320c60368.png">

4) Click on the Key field and change the name. For example enter the key name of **action**, then tab to the value entry field. The entry form changes to the style illustrated below.

<img width="290" alt="HTTP Send Key name issue" src="https://user-images.githubusercontent.com/86308191/235373709-68a575a4-5c98-478c-89aa-26ec858c4e7e.png">

The extra parameter entry elements are shown. 

**Expected behavior**
To enter user specified parameter names such that external equipment with a restful api can be sent a control message. For example:

`http://192.168.100.101:80/config?action=set&paramid=eParamID_VideoInSelect&value=0`

**Test Environment:**
macOS version 12.6.5 running SuperConductor version 0.11.0-alpha.3

**Comment by nytamin** [comment]
Thanks!
This will be fixed in the next (pre-)release

**Comment by amwtech** [comment]
Johan,
Thanks for the feedback. I have since seen a similar error that you may already have fixed whilst looking at issue #144.

If you add a parameter placeholder to an HTML template item, a key/value parameter cannot be removed by using the red dustbin on the parameter. I intended to add just one key/value pair but accidentally added two, then I was unable to delete either.

Andy

**Comment by nytamin** [comment]
Ah, yeah that's a good observation too!

I've made a fix for that as well, it'll be in v0.11.0-alpha.4
