### ISSUE TITLE
How TSR-Bridge works and what is it used for?

### ISSUE THREAD

**Issue by kissgyula** [SuperFlyTV/SuperConductor#150]
I do not fully understand how the TSR-bridge works and what it is for. My first thought was that the same playlist could be accessed from several remote computers. But on the one hand, I haven't been able to set it up yet, or it's not possible. I also don't understand what is the difference between the TSR-brige client and server? Only the internal bridge could connect and only to the local casparcg server. Can someone explain this to me? By the way, is it possible to control the same playlist from several computers?

**Comment by nytamin** [comment]
>By the way, is it possible to control the same playlist from several computers?

Not at the moment, this is might be possible in a future version though.
