### ISSUE TITLE
React error client 

### ISSUE THREAD

**Issue by sater07** [SuperFlyTV/SuperConductor#152]
![Error 2023-06-16 112315 (1).png](https://github.com/SuperFlyTV/SuperConductor/assets/46552145/14a2e734-fd24-49b3-96c3-6d1cfd946edc)

**Comment by nytamin** [comment]
Hi @sater07! Thank you for reporting this, unfortunately the error message isn't visible in the screenshot.

 If the error happens again, please click on the link that says "Please click here to report the bug" or copy the error text and paste it.

**Comment by sater07** [comment]
![20230616_123918.jpg](https://github.com/SuperFlyTV/SuperConductor/assets/46552145/c41fa5c4-ad14-40fc-8e60-45610b2a25ed)

**Comment by nytamin** [comment]
Thank you, I'll look into it!

**Comment by sater07** [comment]
Thanks!!!🙂

**Comment by nytamin** [comment]
This should be fixed now, in v0.11.1. If you see the error again, please reopen this issue.
