### ISSUE TITLE
Feature request: resizable sidebar

### ISSUE THREAD

**Issue by Bohoaush** [SuperFlyTV/SuperConductor#160]
**Is your feature request related to a problem? Please describe.**
When content of the sidebar is wider than the sidebar, for example when editing GDD fields, it's not simple to use. And if you don't have mouse with side scrolling, you can't see the contents at all.

**Describe the solution you'd like**
Allow user to resize the sidebar, and ~~add a horizontal scrollbar.~~ EDIT: Just found out a horizontal scrollbar is already there, but it is not convenient to have to scroll down to move to the right and then you need to figure out where you was. So maybe if there is a way to pin it to be always visible, that would be good.

Or alternatively change the way "GDD editor" is displayed

**Additional context**
![Screenshot_20230714_122800](https://github.com/SuperFlyTV/SuperConductor/assets/43301403/4d9a8a13-1e87-42d5-b379-527042dfc272)

**Comment by nytamin** [comment]
This is now available in [Release v0.12.0-alpha.3](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.12.0-alpha.3)
