### ISSUE TITLE
GDD Array Content is Duplicated

### ISSUE THREAD

**Issue by jeffrapp** [SuperFlyTV/SuperConductor#178]
**Describe the bug**
 I've been able to track this down to a possible change between 0.12.0-alpha.0 and 0.12.0-alpha.1.  If a CasparCG template is providing GDD to SuperConduction, and that GDD description file contains an array, the array data will be duplicated when edited.  Losing focus to the text field or clicking the trash can icon seems to be all it takes to cause this bug. 

**To Reproduce**
1. Open 0.12.0-alpha.1 or 0.12.0-alpha.3
2. Add a CasparCG template with a GDD file that contains an array within the properties
3. Add the first item to the GDD array.  Pressing tab should create a new item, now listed as "0"
4. Populate the new item, and press tab again.  You should now have 4 items visible within the array, with the item originally created being shown twice.  Repeat this step again to see items in the list duplicate.

**Expected behavior**
When I add an item to the list, only a single blank item should be created. 

**Screenshots**
![out2](https://github.com/SuperFlyTV/SuperConductor/assets/1727323/24bc4635-f0b8-4f61-b6e9-962fc1cc19f9)

<img width="841" alt="image" src="https://github.com/SuperFlyTV/SuperConductor/assets/1727323/a550b652-93ec-408f-b213-41aa985e58a7">
<img width="841" alt="image" src="https://github.com/SuperFlyTV/SuperConductor/assets/1727323/0973b727-7bcf-4025-90fb-81d4d8e681e8">
<img width="841" alt="image" src="https://github.com/SuperFlyTV/SuperConductor/assets/1727323/bb8d5636-e35e-43fc-b1a4-2db4e03d6ad1">
<img width="841" alt="image" src="https://github.com/SuperFlyTV/SuperConductor/assets/1727323/ca677abd-264d-4ccf-9227-9953e49f84e4">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Reproduced on 14.0 & 13.4.1

**Additional context**
Sample project here: [ArrayTest.zip](https://github.com/SuperFlyTV/SuperConductor/files/13208075/ArrayTest.zip)

**Comment by nytamin** [comment]
Thanks for reporting this!
We [made a fix for this in the develop branch](https://github.com/SuperFlyTV/SuperConductor/pull/175) a few days ago, I'll make a note to patch the main version too.

**Comment by nytamin** [comment]
This is now fixed in [Release v0.12.0-alpha.4](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.12.0-alpha.4)
