### ISSUE TITLE
Question: Usage with CasparCG

### ISSUE THREAD

**Issue by HadesXR-Git** [SuperFlyTV/SuperConductor#181]
Hi

Sorry for being a beginner here, but is there any documentation regarding the setup and usage with CasparCG?

i've been trying for months to getting this to work with CasparCG. But the resources tab is just empty even when CasparCG is connected to Superconductor

Thanks

**Comment by nytamin** [comment]
Hey! Yeah we should write a getting started quide somewhere!
Do you have the CasparCG media scanner running alongside CasparCG? 
It is needed to expose the templates & media.
Latest version:
https://github.com/CasparCG/media-scanner/releases

**Comment by HadesXR-Git** [comment]
alright, i got the media scanner running now, but it's still empty. is there any steps/commands that i missed while configuring the media scanner? (i followed the steps on the media scanner' page)

Media are showing up in the CasparCG' client, but not at SuperConductor. I'm using the same default config file as the server btw

**Comment by nytamin** [comment]
Regarding the media scanner, there's not much to configure. I just place it in the CasparCG folder and run it, it'll pick up Caspars config and "it just works".

Are you running superconductor on the same machine as Caspar? If not, check that port 5250 (Caspar) and 8000 (scanner) area open in firewall. Also check that url http://ip-adress/media is accessible.

Try opening superconductor from command line/terminal. When you reload media in SC are there errors in the terminal?

Which version of superconductor are you running? Which OS? and which version of CasparCG & scanner?

**Comment by HadesXR-Git** [comment]
> Regarding the media scanner, there's not much to configure. I just place it in the CasparCG folder and run it, it'll pick up Caspars config and "it just works".

funnily enough, the media scanner wont even work if i put it on the same folder as the server folder. so it's running from different folder now


> Are you running superconductor on the same machine as Caspar? If not, check that port 5250 (Caspar) and 8000 (scanner) area open in firewall. Also check that url http://ip-adress/media is accessible.

no, it's on same machine


> Try opening superconductor from command line/terminal. When you reload media in SC are there errors in the terminal?

i dont think the error comes from the SC



> Which version of superconductor are you running? Which OS? and which version of CasparCG & scanner?

SC: v0.11.1, OS: Windows 10 22H2 x64, CCG Server: v2.0.7 Stable, CCG MediaScanner: v1.3.0


im having a suspect now about the old version of CCG Server, i'll try to update it to the latest later and give some updates here if something happpened

**Comment by nytamin** [comment]
Ah, Caspar 207 is pretty old by now, try with 2.3+

**Comment by HadesXR-Git** [comment]
This is what i did for today,

- upgraded the CasparCG Server to v2.3.3 LTS
- set the media-server port to 8000. **note: media-scanner _will not work_ if the media server-port is not 8000**
- set the AMCP port the same as SuperConductor' bridge which is mine, is 5251 (i changed the port number because 5250 is already used)

And guess what? It's finally working!

![Untitled_anon](https://github.com/SuperFlyTV/SuperConductor/assets/66524055/b6a8730c-027d-4137-afac-efa7c05a2808)
