### ISSUE TITLE
Rundown starts playing unexpectedly when Weekly schedule is activated

### ISSUE THREAD

**Issue by 7u5a** [SuperFlyTV/SuperConductor#182]
**Describe the bug**
Rundown starts playing when schedule is activated

**To Reproduce**
1. Create a rundown
2. Schedule for today 21:00:00
3. Activate schedule
4. Rundown starts playing, regardless of the scheduled day and time...

**Expected behavior**
Expect the rundown to start at the scheduled day and time.

**Screenshots**
![fe936c39af8f7e8f657a440733f453bf0c629882](https://github.com/SuperFlyTV/SuperConductor/assets/89579091/3f1a7958-3d53-4a8c-8416-a17754989be1)
![ac48d290483b7c277eea49e26739e0309ce04259](https://github.com/SuperFlyTV/SuperConductor/assets/89579091/e0364a90-23ca-4347-9c5c-4e7d6fba7fae)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.11.1 and alpha version

**Comment by 7u5a** [comment]
I testet a bit more.
It seems when you chose weekly in the schedule, it fucks up.
![image](https://github.com/SuperFlyTV/SuperConductor/assets/89579091/9a3055c7-dd65-4407-a175-b0369d9228c6)
The clock is 17:25 right now, and when weekely turns on, there is 24hr to playlist starts...

When daily and repeat every X day 7, it's okay
![image](https://github.com/SuperFlyTV/SuperConductor/assets/89579091/06ec0475-1600-4dc9-9628-27cbca5949a9)

**Comment by nytamin** [comment]
Thanks for reporting this!
There seemed to be a bug in the calculation of the weekly repeating function. I've pushed a fix in the [0.11.2 version](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.11.2).

**Comment by 7u5a** [comment]
> Thanks for reporting this! There seemed to be a bug in the calculation of the weekly repeating function. I've pushed a fix in the [0.11.2 version](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.11.2).

I'll test it!
