### ISSUE TITLE
closing playout when close of rundown

### ISSUE THREAD

**Issue by 7u5a** [SuperFlyTV/SuperConductor#184]
**Describe the bug**
When you have made a rundown, set it to play and want's to close rundown, it stops playing the rundown.
It's a problem if you have set a rundown to play, after a restart.

**To Reproduce**
Set rundown to play and close it afterwards

**Expected behavior**
I would like to just keep it playing.

**Screenshots**
![image](https://github.com/SuperFlyTV/SuperConductor/assets/89579091/e86d4138-8c82-4544-95a6-c8f0d4e885bc)

**Comment by nytamin** [comment]
This behaviour is not a bug per se, but rather how the application is currently designed.
When you close a rundown, its content is deactivated and so stops playing.

If you think this behaviour should be changed, please open a [Feature Request](https://github.com/SuperFlyTV/SuperConductor/issues/new/choose) and describe your use case and we'll consider it for a future version.

**Comment by 7u5a** [comment]
> This behaviour is not a bug per se, but rather how the application is currently designed. When you close a rundown, its content is deactivated and so stops playing.
> 
> If you think this behaviour should be changed, please open a [Feature Request](https://github.com/SuperFlyTV/SuperConductor/issues/new/choose) and describe your use case and we'll consider it for a future version.

OK
I'll think about it.

**Comment by 7u5a** [comment]
@nytamin so for rundowns playout, you need to have them open in top of window?
