### ISSUE TITLE
Playout no longer working after update to 0.11.2

### ISSUE THREAD

**Issue by ZBlackw1** [SuperFlyTV/SuperConductor#187]
**Describe the bug**
After the auto-update from 0.11.1 to 0.11.2 is completed, when I click to play an element in Superconductor, it appears as if it is playing (timer counting, red bar moving along the clip, etc.) but nothing actually comes out of the outputs of the server. The server console also does not log that it received a play message from Superconductor. Playout works fine when I roll back to Version 0.11.1 or use the official CasparCG client

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Superconductor Version: 0.11.2
 - CasparCG Server Version: 2.3.3 LTS

**Additional context**
The CasparCG Server is running on the same machine as Superconductor.

**Comment by nytamin** [comment]
Hi! Thanks for reporting this.
I'm not able to find any issues with playout when testing the 0.11.2 version, unfortunately.

Does the CasparCG show up as connected (green) in the GUI?
![image](https://github.com/SuperFlyTV/SuperConductor/assets/15196563/8e46058e-8e91-4124-863f-6e6b62b9c84c)

If possible, could you export and send me your project file (Home/Project -> Export fo file)? You can email me at johan@superfly.tv.

**Comment by ZBlackw1** [comment]
Yes, CasparCG shows as green in the GUI and the sidebar shows all of the available media on the server. I just exported my project file and will send it in a moment. Sorry it took me so long to get back to you on this. I had to wait until I was back in the studio after the weekend.

**Comment by ZBlackw1** [comment]
So, after some more testing and experimentation, I have some new info. I installed SuperConductor 0.11.2 on another one of our PCs in the control room and pointed it to the CasparCG Server. This instance works and plays media as expected. However, the instance running on the same machine as the server still does not work. Hopefully, this can help narrow down the search for a problem.
Thanks,
Zach

**Comment by nytamin** [comment]
Hmm, perhaps there could be a clue in your logs? Is there something in there that looks odd?

(The log files are written to `Documents\SuperConductor\Logs`)

**Comment by ZBlackw1** [comment]
SuperConductor is pointed at the IP of ```127.0.0.1``` but there is no change if I try it with the machines network IP. Looking at the logs, there are many errors, most of them from resolveTimeline with an error saying that the object is not unique. I will reply to my email from before with the project file and attach my log file from today if that helps.

Thanks,
Zach

**Comment by nytamin** [comment]
Thanks for sending me your logs @ZBlackw1 !
I think I've figured out what was wrong, please give the latest version ([0.11.3](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.11.3)) a spin and let me know if playout works for you now.

**Comment by ZBlackw1** [comment]
0.11.3 does work for me. Thanks for all of your help fixing this bug.
