### ISSUE TITLE
Question: How does one start playing from somewhere inside the part?

### ISSUE THREAD

**Issue by pbelbin** [SuperFlyTV/SuperConductor#202]
**Describe your question**

I have a HyperDeck, and I have a video clip that is too long.  eg: 5:30 or so.  But, I want to stop at some point prior to the end, to omit the trailing portion.  

I don't know exactly how much time I need to omit, so I need to eyeball it.

Seems like currently, all I have the ability to do is hit 'play' (from the beginning), pause/resume and stop.

I want to be able to set a 'play from' point while editing the part, hit play, then be able to stop and perhaps re-start from the 'play from' to see that my adjustments to the duration are correct & repeat as needed.

How is this done?

**Comment by nytamin** [comment]
SuperConductor uses the [Timeline-State-Resolver](https://github.com/nrkno/sofie-timeline-state-resolver) library to control playback. Unfortunately, it currently does not support _seeking_ into clips for hyperdeck (only for CasparCG).
To solve this, one would have to open a PR to [TSR](https://github.com/nrkno/sofie-timeline-state-resolver) to add support for seeking into files ([somewhere around here](https://github.com/nrkno/sofie-timeline-state-resolver/blob/master/packages/timeline-state-resolver/src/integrations/hyperdeck/index.ts#L598)).

**Comment by pbelbin** [comment]
Hmmmmmm.  That may be *part* of the solution.

But, even if you don't have a HyperDeck playout device, and are using CasparCG, how does one initiate playout partway through the part?

Is there a way to point at a location in the part and cause playout to start from that point in the part?

Or, is there a way to drag the vertical line that shows up during playout of a part and drag it to a different location, and continue from there?

**Comment by pbelbin** [comment]
@nytamin ,

even if the part is made up of lots of smaller timeline items, it seems that currently, there's still no way to ask for the playout of a part to start at 4:30 into the 5 minute long part, and have it pick up playout at the start of the next item in the part?

I tried using CasparCG, and it still seems there is no way to start playout from somewhere arbitrary *within* the part by using the mouse to indicate where playout should start.

Is there another way to do this currently, or is this functionality that's yet to become available, and should be a feature request?

**Comment by nytamin** [comment]
Currently, you can set the Seek property in on CasparCG clip to start playing from that time of the clip. 
There is this FR to make the GUI more intuitive for setting the seek time (ie by dragging the inpoint in the timeline view) : https://github.com/SuperFlyTV/SuperConductor/issues/200

There currently isn't any feature request to start playing a part from a place within it, feel free to write one if you'd like!

**Comment by pbelbin** [comment]
Just FYI, I have opened a feature request for this:

https://github.com/SuperFlyTV/SuperConductor/issues/203
