### ISSUE TITLE
SuperConductor crashes when connecting a Streamdeck

### ISSUE THREAD

**Issue by njrl** [SuperFlyTV/SuperConductor#212]
**Describe the bug**
When I start the Application with a Steamdeck connected it crashes immediately after loading the GUI.
When I start the App. with a Steamdeck connected and have the Panel(s) disabled beforehand it starts, until the moment when enable the Panel(s) in the bridge setting again.

`Update for version 0.11.3 is not available (latest version: 0.11.3, downgrade is allowed).
checkForUpdatesAndNotify called, downloadPromise is null
**
ERROR:../vendor/8.13.3/linux-x64/include/vips/VImage8.h:174:VipsObject* vips::VObject::get_object() const: assertion failed: (!vobject || VIPS_IS_OBJECT( vobject ))
Bail out! ERROR:../vendor/8.13.3/linux-x64/include/vips/VImage8.h:174:VipsObject* vips::VObject::get_object() const: assertion failed: (!vobject || VIPS_IS_OBJECT( vobject ))
[1]    3524324 IOT instruction (core dumped)  ./SuperConductor-0.11.3-Linux-Executable.AppImage --no-sandbox`

**Desktop:**
 - OS: Ubuntu 24.04.1 LTS
 - Version: 0.11.3-Linux-Executable.AppImage

**Additional comment**
Would be nice to have a Companion Plugin with the features of a direct connected streamdeck.

regards

**Comment by nytamin** [comment]
Hi!
Thanks for the bug report! This seems to be an issue deep down in `libvips` which is a library used by `sharp`, which SuperConductor uses to draw the StreamDeck images.

I don't think I will be able to troubleshoot and fix this myself unfortunately, but I you find a solution and make a PR I'd be happy to merge it!

Something you _could_ try is to build your own version where you update `sharp` to its latest version, since [that uses an updated libvips version](https://github.com/lovell/sharp/blob/main/docs/changelog.md).

**Comment by njrl** [comment]
thanks for the response, but maybe i need more advise.
when i do a clean build of SC, the binary works fine with the known bug.
then i've tryed to
`npm install sharp`
which doesn't work because of version conflicts. then i did 
`npm install sharp --force (which installs the latest 0.33.)
yarn build
yarn build:binary`
which results in a broken binary.

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/tmp/.mount_SuperCj43jA2/resources/app.asar/node_modules/@shared/peripherals/node_modules/sharp/lib/sharp.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_SuperCj43jA2/resources/app.asar/node_modules/@shared/peripherals/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
`

**Comment by nytamin** [comment]
Thanks for spending the time!
Since this is a mono-repo, you'll have to update `sharp` for the correct module/package, not on the root package.

Go to `shared/packages/peripherals/package.json` and update the sharp entry in that to latest version (`0.33.5`), then run `yarn` again on the root (to actually install the new dependencies).

**Comment by njrl** [comment]
Good Morning,
I changed the version in `package.json` (devDep. and dependencies)
but even `npm view sharp versions` say's that there ist the 0.33.5 available.
when I do `yarn` I got promtedt to choose:
`Please choose a version of "@types/sharp" from this list: (Use arrow keys)
❯ 0.32.0 
  0.31.1 
`
where 0.32.0 is the hightest available version.

btw:
repo freshly pulled  and 
`nvm version v18.20.4`

**Comment by nytamin** [comment]
Ah, yeah the `@types/sharp` doesn't affect the compiled results and is for development only, it is normal that it lags a few versions behind. Pick whatever is latest for it and try with that (or even leave it be).

**Comment by njrl** [comment]
you're right, it worked.
thx

for completeness:

- `sudo apt install libvips-dev`
- `git clone ...`
- modify the sharp version to 0.33.5 or direct to 0.32.0(which is the highest possible atm) in `shared/packages/peripherals/package.json`
- `yarn`
- `yarn build`
- `yarn build:binary`

**Comment by nytamin** [comment]
Thanks! I'll make sure it's updated in the next version
