### ISSUE TITLE
How to use it with OBS ?

### ISSUE THREAD

**Issue by ProTechEx** [SuperFlyTV/SuperConductor#36]
Hi there,

is there any Documentation regarding the setup and usage with OBS ?

Thanks

**Comment by alvancamp** [comment]
When OBS v28 comes out, obs-websocket v5 will ship with it, eliminating the need for users to separately install it. v28 is currently in beta. I believe that we will need to update the obs-websocket-js dependency in TSR to v5 as well.

**Comment by ogmkp** [comment]
> When OBS v28 comes out, obs-websocket v5 will ship with it, eliminating the need for users to separately install it. v28 is currently in beta. I believe that we will need to update the obs-websocket-js dependency in TSR to v5 as well.
> 
> EDIT: As for no playable OBS items showing up in the resource pane, I have not experienced that issue and am unsure what may be causing it.

Please try to keep backward compatibility with OBS websocket 4.9.1 for OBS 27.2.4.
OBS 28 breaks a lot of features and is not mature enough for production.

**Comment by alvancamp** [comment]
> Please try to keep backward compatibility with OBS websocket 4.9.1 for OBS 27.2.4. OBS 28 breaks a lot of features and is not mature enough for production.

I understand your desire to have SuperConductor keep support for OBS 27, especially considering that OBS 28 upgrades to Qt 6, which breaks any older plugins that linked against Qt 5. The bad news is that keeping obs-websocket protocol v4 compatibility while also supporting v5 of the protocol would be a substantial maintenance burden. The good news is that [obs-websocket v5.0.1](https://github.com/obsproject/obs-websocket/releases/tag/5.0.1) provides v5 of the protocol for OBS 27, which would mean that a SuperConductor based on v5 of the protocol would indeed still be compatible with OBS 27. Does that satisfy your use case?

**Comment by ogmkp** [comment]
Thats a good news, I did not ask the websocket team, but can we use websocket 4 and 5 together ?

**Comment by alvancamp** [comment]
> Thats a good news, I did not ask the websocket team, but can we use websocket 4 and 5 together ?

Yes, the obs-websocket v5.0.1 release I linked to also has downloads for `4.9.1-compat` which will allow you to run v4 and v5 at the same time on OBS 27, albeit on two different ports.

**Comment by ogmkp** [comment]
Thanks for you reply.
