### ISSUE TITLE
Transitions?

### ISSUE THREAD

**Issue by Keksstar** [SuperFlyTV/SuperConductor#37]
Missing the transition effects from the Caspar Client... something I´ve missed or not yet implemented?

**Comment by nytamin** [comment]
Yeah, it's not implemented in the GUI yet, I have a branch where I've been working on adding those, so expect them to be added in the next few weeks 🙂

**Comment by nytamin** [comment]
The addition of transitions have now been published as of version [v0.8.5](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.8.5).
