### ISSUE TITLE
Duration input bugs

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/SuperConductor#39]
**Describe the bug**
Certain entries to the Duration input field have unexpected results.

**To Reproduce**
All of the below cases should be reproducible on any timeline object:

- Sometimes the infinity symbol cannot be edited by typing and the user must either paste in a complete value or use the arrow keys to increment/decrement. Once this is done, the value can be edited. Of note is that this wasn't happening to me earlier today, but now it is happening to myself and another person. I'm unsure what caused the behavior to change or what conditions are required that I'm not seeing.
- Trying to enter a decimal that starts with `0` doesn't work. For example, trying to type in `10.05` will result in `1:05`. Pasting in the complete value works.
- Some time values unexpectedly get replaced with other values when typing. For example, trying to type in `1:16:33` will result in a value of `1:20:33`. Again, pasting in the complete value works.

**Expected behavior**
All of the above cases should work as expected.

**Screenshots**
N/A

**Desktop:**
 - OS: Windows 10 Pro
 - Version 10.0.19044 Build 19044

**Additional context**
All issues are present on the `develop` branch.

**Comment by nytamin** [comment]
Thanks!
All good observations, the logic for interpreting the user-input sure could use some more work..

I've pushed a few fixes to `develop` for the points you've mentioned above.
Could you give it a spin and see if there are any other things you find?

**Comment by nytamin** [comment]
(The fixes mentioned above are also in the release v0.8.4 now)

**Comment by alvancamp** [comment]
I can confirm that all three of the described cases now work as expected. Thank you!!
