### ISSUE TITLE
Can't resize an item with mouse in the timeline

### ISSUE THREAD

**Issue by ogmkp** [SuperFlyTV/SuperConductor#40]
**Describe the bug**
Can't resize with a mouse to set a duration.

**To Reproduce**
1. Add a scene
2. Try to resize with a mouse to set a duration,
3. Need to add duration in the field
4. Can resize the item with mouse in the timeline

**Expected behavior**
Adding items with infinite duration is ok, if we move the size, the item have to adapt a duration.

**Desktop (please complete the following information):**
 - OS: Debian 11
 - 0.8.3 appimage

**Comment by nytamin** [comment]
Thanks for reporting this!

I've pushed [a fix](https://github.com/SuperFlyTV/SuperConductor/commit/a092ebba48173c96c212a91d558737167ca5e0c4) that should fix this to `develop`, so it'll be included in the next version.

**Comment by nytamin** [comment]
(The fix mentioned above are also in the release v0.8.4 now)

**Comment by ogmkp** [comment]
Tested and it works.
Thank you.
