### ISSUE TITLE
Feature request: Add support for existing TSR-device: HTTP (REST)

### ISSUE THREAD

**Issue by nytamin** [SuperFlyTV/SuperConductor#49]
Add support for the existing TSR-Arbitrary HTTP (REST) compatible device in GUI.

The logic is already there in TSR, we just need to implement it in the SuperConductor GUI.

**Comment by alvancamp** [comment]
I believe this was implemented in https://github.com/SuperFlyTV/SuperConductor/commit/32a769535569c388f23a16d19844df986d5398e1.

Also worth noting is that the above commit is a pretty good self-contained example of how to implement a new TSR device in SuperConductor. The only thing it is missing is a good example of interfacing with a real sideloaded device, but that knowledge can be gained from looking at the other files in the [`shared/packages/tsr-bridge/src/sideload`](https://github.com/SuperFlyTV/SuperConductor/tree/master/shared/packages/tsr-bridge/src/sideload) folder.

**Comment by nytamin** [comment]
You are of course correct! Looks like the only thing left to do is to update the README :)

**Comment by alvancamp** [comment]
For something as small as a README update, should I commit to `develop` or just commit directly to `master`?
