### ISSUE TITLE
Feature request: Add support for existing TSR-device: TCP

### ISSUE THREAD

**Issue by nytamin** [SuperFlyTV/SuperConductor#50]
Add support for the existing TSR-Arbitrary TCP-socket compatible device in GUI.

The logic is already there in TSR, we just need to implement it in the SuperConductor GUI.

**Comment by PeterC89** [comment]
Think I've got a working version of this, just need a suggestion for what colour the objects should be.
Current colours are here: https://github.com/SuperFlyTV/SuperConductor/blob/develop/apps/app/src/react/styles/foundation/_colors.scss
@hummelstrand any suggestions?

**Comment by PeterC89** [comment]
Branch here: https://github.com/SuperFlyTV/SuperConductor/tree/feat/tcp-send

**Comment by nytamin** [comment]
This is now done in release [v0.11.0](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.11.0)
