### ISSUE TITLE
Feature request: Show an indicator when timelineObjs overlap

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/SuperConductor#60]
**Is your feature request related to a problem? Please describe.**
It's easy to have timelineObjs overlapping on a layer. This is generally unlikely to be intentional as the behavior isn't clearly defined to the user. Does the first timelineObj play to completion? Does the second timelineObj clobber it? What happens if the first timelineObj starts before the second one _and_ ends after it? Does the second timelineObj clobber the first one only while it is active, and then does it go back to the first one? Etc.

**Describe the solution you'd like**
I'm unsure what the best solution here would be. Perhaps some kind of zebra stripe pattern on the overlapping section?

![Untitled](https://user-images.githubusercontent.com/873012/185969564-b23eb641-aba3-4832-8ed9-1dcb79e8eb46.png)

**Additional context**
Implementing this might be difficult, especially in terms of performance. Part of me is hoping that an "automatic" solution with [CSS `mix-blend-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) might be possible.

Another approach would be to do what most NLEs do, which is prevent overlaps from occurring and instead trim the non-selected clip(s) such that an overlap is never happens.

**Comment by nytamin** [comment]
I think this is a great idea! 🚀

I don't actually think it would be too bad to implement, performance-wise. We just have to make a comparison (per-layer) of timeline-instances to find any overlaps.

Feel free to submit a Pull Request with this, or I might also look into it in the future 👍

**Comment by nytamin** [comment]
This was fixed i https://github.com/SuperFlyTV/SuperConductor/pull/131
