### ISSUE TITLE
Jittery Part moves between Groups

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/SuperConductor#61]
**Describe the bug**
Sometimes moving a Part to a new Group or Transparent Group results in the attempted move jittering up and down while the user's cursor is still.

**To Reproduce**
This issue doesn't always occur, but the below steps seem to be pretty reliable as a repro:
1. Start with an empty rundown
2. Drag a Resource onto the New Group button
3. Add another Part to the same Group by dragging another Resource onto the New Part button within that Group
4. Create a new empty Group under the first one
5. Try to drag the second Part of the first Group to near the top of the second Group

**Expected behavior**
If the user's cursor is still during a drag operation, things shouldn't be moving around underneath it.

**Screenshots**
![ezgif-4-1afa813bfd](https://user-images.githubusercontent.com/873012/185977065-b21e5ffb-fe67-49c3-b4f1-5b52191a2e76.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Pro
 - Version 0.8.4

**Additional context**
The drag move code is... kind of a nightmare. I've tried to fix this bug in the past and walked away defeated. The issue may lie in one or more of these areas:

- [RundownView.tsx#L21-L69](https://github.com/SuperFlyTV/SuperConductor/blob/5f8c02d10795637098a27456ddcf0287e0319acd/apps/app/src/react/components/rundown/RundownView.tsx#L21-L69)
- [GroupView.tsx#L266-L408](https://github.com/SuperFlyTV/SuperConductor/blob/5f8c02d10795637098a27456ddcf0287e0319acd/apps/app/src/react/components/rundown/GroupView/GroupView.tsx#L266-L408)
- [PartView.tsx#L633-L750](https://github.com/SuperFlyTV/SuperConductor/blob/5f8c02d10795637098a27456ddcf0287e0319acd/apps/app/src/react/components/rundown/GroupView/PartView.tsx#L633-L750)
- [PartView.tsx#L751-L805](https://github.com/SuperFlyTV/SuperConductor/blob/5f8c02d10795637098a27456ddcf0287e0319acd/apps/app/src/react/components/rundown/GroupView/PartView.tsx#L751-L805)
- [RundownsStore.ts#L462-L689](https://github.com/SuperFlyTV/SuperConductor/blob/5f8c02d10795637098a27456ddcf0287e0319acd/apps/app/src/react/mobx/RundownsStore.ts#L462-L689)

**Comment by nytamin** [comment]
Yeah, there's a _lot_ of code involved to handle all the various drag operations..

I'm guessing that the wiggling could be avoided if the target-marker-placeholders has a zero-height.

I've pushed a potential fix for this in https://github.com/SuperFlyTV/SuperConductor/commit/bcc539936fa86e3edfc45b566f8b43b37227fdec, could you see if it works for you?

**Comment by alvancamp** [comment]
I can confirm that the wiggling is now gone. There's another related issue that I'm seeing now that might have actually been the root cause of this, but I think it's technically a separate issue so I'll open another ticket for that.

**Comment by alvancamp** [comment]
Oops, re-opening until the branch in question is merged.
