### ISSUE TITLE
Trying to drag a Part between two Groups sometimes results in the Part going below all Groups

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/SuperConductor#63]
**Describe the bug**
There are certain pixels between Groups where, if a dragged Part is hovered over them, the drop indicator appears at the end of the list of Groups instead of between the two Groups, as the user would expect.

**To Reproduce**

1. Start with an empty rundown
2. Drag a Resource onto the New Group button
3. Add another Part to the same Group by dragging another Resource onto the New Part button within that Group
4. Create a new empty Group under the first one
5. Try to drag the second Part of the first Group to the space between the first and second Groups.
6. Observe that on some of those pixels, the drop indicator moves to the end of the Group list instead of being between the first two Groups.

**Expected behavior**
A Part drag operation to the space between two Groups should always result in the Part becoming a new Transparent Group between those two Groups.

**Screenshots**
![ezgif-4-8c9c7396d5](https://user-images.githubusercontent.com/873012/186213616-08e99031-5b76-47b2-9fb8-0243eddbcffe.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Version [`fix/jitter-when-dragging` branch](https://github.com/SuperFlyTV/SuperConductor/tree/fix/jitter-when-dragging)

**Additional context**
Related to #61 and may be the root cause of it as well.

I believe the source of this issue is the fact that the space between Groups is achieved via a CSS `margin`. I believe that margins like this are ignored by the drag and drop system and so the `hover` processing passes through to the `<RundownView>` component, which always places the dropped Part at the end of the Groups list ([RundownView.tsx#L48-L50](https://github.com/SuperFlyTV/SuperConductor/blob/bcc539936fa86e3edfc45b566f8b43b37227fdec/apps/app/src/react/components/rundown/RundownView.tsx#L48-L50)).

The fix may need to involve adding a dedicated `<GroupSpacer>` element that goes between each pair of `<GroupView>` elements, instead of the `<GroupView>` elements using a CSS `margin` to achieve their spacing. `<GroupSpacer>` would need to have the appropriate logic to handle hover and drop events. The end goal here is that there are no gaps and no margins between Groups, because either of those will result in the hover/drop events being handled by `<RundownView>`, which we don't want.

![image](https://user-images.githubusercontent.com/873012/186216427-9231674b-d876-409c-b2ca-f0fa1d71e377.png)

**Comment by nytamin** [comment]
I haven't experienced this bug for quite some time so I _think_ this has been fixed a while ago. Let's reopen this if the bug reappears.
