### ISSUE TITLE
Feature request: ability to disable Streamdeck integration

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/SuperConductor#65]
**Is your feature request related to a problem? Please describe.**
Some users want to run SuperConductor and Companion on the same computer. When both of these programs are running, they fight for control of any connected Streamdecks.

**Describe the solution you'd like**
I'd like the ability to disable the Streamdeck integration, either globally or on a per-Streamdeck basis.

**Additional context**
N/A

**Comment by nytamin** [comment]
Yeah, this is very much needed! 🚀

This would be something that lives in the Bridges-settings.

I'm thinking that (by default) there would be a mode called "Connect to everything automatically", like how it works today.
Then it should be possible to switch to a "Connect manually"-mode where nothing is connected to automatically, but a list of devices show up and the user can choose which to connect to.

Feel free to submit a Pull Request with this, or I might also look into it in the future 👍
