### ISSUE TITLE
Feature request: improve display of "time elapsed" and "time remaining"

### ISSUE THREAD

**Issue by alvancamp** [SuperFlyTV/SuperConductor#70]
**Is your feature request related to a problem? Please describe.**
Currently, these two numbers are just kinda... floating there, with no labels.

![Untitled](https://user-images.githubusercontent.com/873012/186725506-a91c4db4-d862-41ea-bc65-3a245e73e99f.png)

**Describe the solution you'd like**
I'd like to see an improved design for these two pieces of information.

**Additional context**
I'm the one who just shoved those numbers into the top margin and called it a day. Sorry. 😅

**Comment by nytamin** [comment]
I personally haven't had any issues with those numbers, I think they work great! :)
I can see the improvement potential tho, feel free to submit a Pull Request with this, or I might also look into it some in the future 👍

**Comment by PeterC89** [comment]
PR raised as a first attempt on this: https://github.com/SuperFlyTV/SuperConductor/pull/114
![Image](https://user-images.githubusercontent.com/12292660/201909977-6beb6722-1f43-4e8c-9aea-a66b997bfd22.png)

**Comment by PeterC89** [comment]
PR merged, done!
