### ISSUE TITLE
Feature request: Edit multiple things

### ISSUE THREAD

**Issue by nytamin** [SuperFlyTV/SuperConductor#73]
**Describe the solution you'd like**
I would like to be able to select multiple items, and when I edit them in the right pane (like disabling them, or changing a duration) the change should be applied to all.

**Additional context**
Example:
![image](https://user-images.githubusercontent.com/15196563/187030724-f24927ac-d7bd-40b1-bcc9-b09f1d935f10.png)

**Comment by PeterC89** [comment]
@nytamin @alvancamp First attempt at working on this is in this branch https://github.com/SuperFlyTV/SuperConductor/tree/feat/multiple-edit

It probably won't at the moment as some further changes need to be made to other components but you can now edit / delete multiple parts and the lock state of each part (or parent group) is respected.

Thoughts and feedback welcome as I move onto multiple groups (and maybe objects...)

**Comment by nytamin** [comment]
This is now released in[ v0.11.0](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.11.0)
