### ISSUE TITLE
MacOS: App hangs on quit

### ISSUE THREAD

**Issue by Saftret** [SuperFlyTV/SuperConductor#82]
**Describe the bug**
When quitting on a Mac (command+Q) the app stays in a non responsive state. Closing the window (command+W) will result in the behavior expected from command+Q (app quits). 

**To Reproduce**
1. Quit app on Mac OS. From app menu or with command + Q.

**Expected behavior**
As a Mac user I expect command+W to close the window but to leave the app running. Command+Q is expected to quit the app entirely. 

**Desktop (please complete the following information):**
 - OS: MacOS on Apple Silicon
 - Version 13

**Additional context**
Related to app event handling on MacOS: [https://www.electronjs.org/docs/latest/api/app#event-window-all-closed](https://www.electronjs.org/docs/latest/api/app#event-window-all-closed)

**Comment by nytamin** [comment]
This was fixed in https://github.com/SuperFlyTV/SuperConductor/pull/85
