### ISSUE TITLE
Code compilation problem 

### ISSUE THREAD

**Issue by rclabs-dev** [SuperFlyTV/SuperConductor#87]
**Describe your question**
I did download source code from github and follow instruction to "compile" the code as cited at https://github.com/SuperFlyTV/SuperConductor/blob/master/doc/FOR_DEVELOPERS.md.

But in this process several errors occur. 

I would like to know if the actual way of compiling the code is correct as mentioned in the documentation (link above)?

Due to the inumerous errors that appear, I did'nt paste here (for the moment).

What are the scenarios regarding of the artefacts version I should to compile it like Operation System, node, npm, yarn and others to ensure a build free of critical errors.

It's all. Thanks in advance.

Regivaldo Costa
--

**Additional context**
- I'm using Ubuntu 22.04 (I try it on Debian 11.5 too)
- First I used node v14.20.0 (as inidicated in .nvmrc); npm  v6.14.17 and yarn v.3.2.3, but several erros occur;
- Second I remove node_modules, change to node v16.17.0, npm v8.15.0 and yarn 3.2.3, but the errors continue as first action.

**Comment by alvancamp** [comment]
Hello! 👋 

Are `build-essential` and Python 3 installed on the Linux system in question? And could you paste the first two dozen or so lines of the build error log output to help us figure out what the issue may be?

Thanks for trying out SuperConductor! 🙂

**Comment by rclabs-dev** [comment]
Hi dear,

Thank you for your reply.

So, build-essential and python3 already installed:
-----------
rcosta@carbon301de:~/SuperConductor$ **dpkg -l | grep build-essential**
ii  build-essential                       12.9ubuntu3                                  amd64        Informational list of build-essential packages
rcosta@carbon301de:~/SuperConductor$ **python3 --version**
Python 3.10.4
-----------

Regarding the errors that I have now are:

-----------
rcosta@carbon301de:~/SuperConductor$ **yarn**
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @octokit/rest@npm:16.43.2 doesn't provide @octokit/core (p84523), requested by @octokit/plugin-request-log
➤ YN0002: │ superconductor-monorepo@workspace:. doesn't provide eslint (pf56b8), requested by eslint-plugin-react-hooks
➤ YN0002: │ superconductor-monorepo@workspace:. doesn't provide eslint (pd6525), requested by eslint-plugin-react
➤ YN0002: │ superconductor@workspace:apps/app doesn't provide prop-types (pde19c), requested by react-toggle
➤ YN0002: │ superconductor@workspace:apps/app doesn't provide tiny-warning (pbe67e), requested by formik-mui
➤ YN0002: │ superconductor@workspace:apps/app doesn't provide typescript (p7ca0e), requested by ts-loader
➤ YN0002: │ tsr-bridge@workspace:apps/tsr-bridge doesn't provide prop-types (pc426d), requested by react-toggle
➤ YN0002: │ tsr-bridge@workspace:apps/tsr-bridge doesn't provide typescript (p27bb9), requested by ts-loader
➤ YN0002: │ webpack-dev-server@npm:4.7.3 [11019] doesn't provide @types/express (p8e0d1), requested by http-proxy-middleware
➤ YN0002: │ webpack-dev-server@npm:4.7.3 [7ceaa] doesn't provide @types/express (p8fc71), requested by http-proxy-middleware
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 473ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 128ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 331ms
➤ YN0000: Done with warnings in 3s 104ms
rcosta@carbon301de:~/SuperConductor$ **yarn setup**
lerna notice cli v3.22.1
lerna info bootstrap root only
Unknown Syntax Error: Unsupported option name ("--mutex").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'superconductor-monorepo'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'superconductor-monorepo'
rcosta@carbon301de:~/SuperConductor$ **yarn start**
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @octokit/rest@npm:16.43.2 doesn't provide @octokit/core (p84523), requested by @octokit/plugin-request-log
➤ YN0002: │ superconductor-monorepo@workspace:. doesn't provide eslint (pf56b8), requested by eslint-plugin-react-hooks
➤ YN0002: │ superconductor-monorepo@workspace:. doesn't provide eslint (pd6525), requested by eslint-plugin-react
➤ YN0002: │ superconductor@workspace:apps/app doesn't provide prop-types (pde19c), requested by react-toggle
➤ YN0002: │ superconductor@workspace:apps/app doesn't provide tiny-warning (pbe67e), requested by formik-mui
➤ YN0002: │ superconductor@workspace:apps/app doesn't provide typescript (p7ca0e), requested by ts-loader
➤ YN0002: │ tsr-bridge@workspace:apps/tsr-bridge doesn't provide prop-types (pc426d), requested by react-toggle
➤ YN0002: │ tsr-bridge@workspace:apps/tsr-bridge doesn't provide typescript (p27bb9), requested by ts-loader
➤ YN0002: │ webpack-dev-server@npm:4.7.3 [11019] doesn't provide @types/express (p8e0d1), requested by http-proxy-middleware
➤ YN0002: │ webpack-dev-server@npm:4.7.3 [7ceaa] doesn't provide @types/express (p8fc71), requested by http-proxy-middleware
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 505ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 935ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 138ms
➤ YN0000: Done with warnings in 2s 757ms
No matches found: "--scope=@shared/*"
-----------

I would appreciate if I could guide me in some direction that will solve the problem.

Many thanks!

Regivaldo Costa

**Comment by alvancamp** [comment]
I wonder if the problem is that a Yarn version other than 1.x is being used. Do these issues persist with Yarn 1.x?

**Comment by rclabs-dev** [comment]
Hi dear,

The version is:

rcosta@carbon301de:~/SuperConductor$ yarn --version
3.2.3

**Comment by nytamin** [comment]
Hi!
Sorry to hear that you're having problems. To answer your initial question
>I would like to know if the actual way of compiling the code is correct as mentioned in the documentation (link above)?
Yes, it should be. But I have to admit I haven't personally spent much time developing it on Linux (not sure if you did, @alvancamp?) 

The workflow we use to generate the binaries for each release is this:
https://github.com/SuperFlyTV/SuperConductor/blob/master/.github/workflows/create-release.yaml#L71, so at least we know it works in that environment.

From a quick googling, the problem seems to be the same as described here:

**Comment by alvancamp** [comment]
> Yes, it should be. But I have to admit I haven't personally spent much time developing it on Linux (not sure if you did, @alvancamp?)

Yes, the build steps work on Linux, as it is used in CI.

**Comment by rclabs-dev** [comment]
Dear @nytamin and @alvancamp ,

Thaks for the help.

I will try to build it again, but checking the additional information.

Best regard,

Regivaldo Costa
--
