### ISSUE TITLE
Atem Input field is capped to 99

### ISSUE THREAD

**Issue by SNRSE** [SuperFlyTV/SuperConductor#93]
**Describe the bug**

**To Reproduce**
1. add an Atem Device to the internal Bridge 
2. Add a  "ATEM ME 1" Timeline objekt 
3. Try to enter any number higher 99 into the Input field for Input

**Expected behaviour**
The Input field should at least allow inputs up to 99999
to allow to take Supersource or a Mediaplayer 
See the link for IDs of super source -> https://atem.julusian.dev/enums
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.9.2

**Comment by nytamin** [comment]
Thanks for reporting this!
I've pushed a fix for this in version 0.9.3.
